### ISSUE TITLE
Multiple Rear Cameras producting White Canvas

### ISSUE THREAD

**Issue by KhaosArbiter** [KhaosArbiter/modern-react-qr-reader#1]
This appears to be an issues only affecting models of phones where there are multiple rear cameras (Tested against an iPhone, LG V60, Samsung Galaxy Note 10 Plus, and Pixel 4a)

**Comment by KhaosArbiter** [comment]
Fixed this by manually implementing the pull request at https://github.com/JodusNodus/react-qr-reader/pull/164

**Comment by axelraymundo** [comment]
> Fixed this by manually implementing the pull request at [JodusNodus/react-qr-reader#164](https://github.com/JodusNodus/react-qr-reader/pull/164)

Sorry for asking this here but how can I manually implement this pull request.
