### ISSUE TITLE
Update Example for component State Change

### ISSUE THREAD

**Issue by boycesm** [KhaosArbiter/modern-react-qr-reader#2]
Can you add this to the example file? 

handleScan = data => {
    if (data) {
      this.state.result = data;
      **console.log(this.state.result);
      this.setState({result: data});**
    }
  }
  
  This would refresh the <p>{this.state.result}</p> on new scan and also console log the result for troubleshooting issues should someone not get a change to their page, but the scan did in fact work again this is just for the example and I'm somewhat of a novice, but out of the box this would tell me if the code was working for what I needed it to do. 
  
  Thanks for reviving this from the other dead repo KhaosArbiter!

**Comment by KhaosArbiter** [comment]
I'll get this added, I'm sorry for the delayed response on this, it's been a busy month.
