### ISSUE TITLE
fix issue with chrome freezing on android

### ISSUE THREAD

**Issue by jeznag** [KhaosArbiter/modern-react-qr-reader#4]
Fix for https://github.com/JodusNodus/react-qr-reader/issues/185

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/modern-react-qr-reader/lib/index.js b/node_modules/modern-react-qr-reader/lib/index.js
index 27330bc..f02698a 100644
--- a/node_modules/modern-react-qr-reader/lib/index.js
+++ b/node_modules/modern-react-qr-reader/lib/index.js
@@ -235,7 +235,11 @@ module.exports = (_temp = _class = function (_Component) {
 
       var streamTrack = stream.getTracks()[0];
       // Assign `stopCamera` so the track can be stopped once component is cleared
-      this.stopCamera = streamTrack.stop.bind(streamTrack);
+      this.stopCamera = () => {
+        setTimeout(() => {
+          streamTrack.stop();
+        }, 2000);
+      }
 
       preview.addEventListener('loadstart', this.handleLoadStart);
 
diff --git a/node_modules/modern-react-qr-reader/src/index.js b/node_modules/modern-react-qr-reader/src/index.js
index 879993e..3e5f13c 100644
--- a/node_modules/modern-react-qr-reader/src/index.js
+++ b/node_modules/modern-react-qr-reader/src/index.js
@@ -195,7 +195,11 @@ module.exports = class Reader extends Component {
 
     const streamTrack = stream.getTracks()[0]
     // Assign `stopCamera` so the track can be stopped once component is cleared
-    this.stopCamera = streamTrack.stop.bind(streamTrack)
+    this.stopCamera = () => {
+      setTimeout(() => {
+        streamTrack.stop();
+      }, 2000);
+    }
 
     preview.addEventListener('loadstart', this.handleLoadStart)
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by KhaosArbiter** [comment]
Thank you for the input.  Can you please submit a pull request for the changes and I will be happy to test and implement this.  Is this in regard to the browser freezing due to OOM issues if it's been running for a bit without a successful scan or some separate issue?

**Comment by DaemonAlchemist** [comment]
I'm getting this issue as well:  If I close the reader by removing the QRReader component once I get a successful scan, the browser freezes.  It happens even if the reader has only been open a few seconds.

**Comment by KhaosArbiter** [comment]
Merged your pull request and tested, it works great.  NPM Package has been updated as well.  Thank you @jeznag

**Comment by KhaosArbiter** [comment]
This actually still seems to be an issue.  Reopening this to take a closer look.

**Comment by DaemonAlchemist** [comment]
Well, the original fix seems to work for my use case.

**Comment by KhaosArbiter** [comment]
Can I ask what version of Chrome you are running and on what device?  I just want to compare and rule out it being a local issue.

**Comment by KhaosArbiter** [comment]
The issue comes and goes on a LG V60 running Chrome 89.0.4389.90

**Comment by KhaosArbiter** [comment]
I actually think this might be a separate issue.  I am going to close this again, that is my mistake.  It seems to work, but if I refresh the page for some reason it will no longer scan.  It doesn't freeze though.  I have to switch to a different page with an instance of the component and it works fine, but trying to scan different codes after it's been removed from the page seems to not work.

**Comment by DaemonAlchemist** [comment]
My test device is a Pixel 2 running Chrome 89 on Android 11
