### ISSUE TITLE
TypeError due to missing 2D context when trying to call drawImage

### ISSUE THREAD

**Issue by charleskoehl** [KhaosArbiter/modern-react-qr-reader#8]
Hey thanks for creating this! We've been using react-qr-reader and getting this error all the time:

`null is not an object (evaluating 'm.drawImage')`

In our PWA, we show the component in a Material-UI dialog. The only property besides onError and onScan we're setting is showViewFinder={false}

We've been capturing it in production with sentry.io. The column on the right shows statistics for all events, while the rest is for the latest event.

![image](https://user-images.githubusercontent.com/887025/111992008-0442c680-8ab9-11eb-9208-c3036b49a824.png)

**Comment by charleskoehl** [comment]
Sorry, this is happening in react-qr-reader.  We tried modern-react-qr-reader but had to go back to react-qr-reader because it had more problems than react-qr-reader. I'll add those issues here soon.

**Comment by KhaosArbiter** [comment]
Please do add the issues here.  The goal is to get all these issues cleaned up, and the bug reports would be extremely helpful.
